pipeline {
      agent any
      stages {
            stage('Init') {
                  steps {
                        echo 'Hi, this is Anshul from LevelUp360'
                        echo 'We are Starting the Testing'
                  }
            }
            stage('Build') {
                  steps {
                        echo 'Building Sample Maven Project'
                  }
            }
            stage('Deploy') {
                  steps {
                        echo "Deploying in Staging Area part 1"
                  }
            }
            stage('Deploy Production') {
                  steps {
                        echo "Deploying in Production Area part 2"
                  }
            }
            stage('Deploy Production  1') {
                  steps {
                        echo "Deploying in Production Area part 3"
                  }
            }
      }
}
